version: '3.8'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend.dev
  #   container_name: back-end
  #   restart: on-failure
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./back-end:/app
  #     - /app/node_modules
  #   tty: true
  #   stdin_open: true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: front-end-diverso
    restart: on-failure
    ports:
      - "3004:3004"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    # depends_on:
    #   - backend
    tty: true
    stdin_open: true